spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:questions}
    username: ${MYSQL_USERNAME:questions}
    password: ${MYSQL_PASSWORD:db5KDBD3G8DeJ3Y6}
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080 