spring:
  datasource:
    url: jdbc:mysql://103.26.77.66:11085/questions?useSSL=false&serverTimezone=UTC
    username: root
    password: cc7cd2086a482520
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8080 