spring:
  datasource:
    url: jdbc:mysql://2.tcp.vip.cpolar.cn:11085/questions?useSSL=false&serverTimezone=UTC
    username: questions
    password: db5KDBD3G8DeJ3Y6
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080 

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher 