name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 101.34.34.218
          username: root
          password: ^SZ.5qy7xfw4[
          port: 22
          script: |
            cd /www/wwwroot/questions_back
            git pull
            mvn clean package -DskipTests
            pid=$(ps -ef | grep question-bank | grep -v grep | awk '{print $2}')
            if [ -n "$pid" ]; then
              kill -9 $pid
            fi
            nohup java -jar target/question-bank-1.0-SNAPSHOT.jar --spring.profiles.active=prod > nohup.out 2>&1 &