name: Deploy to Server

on:
  push:
    branches: [ main ]  # 或者 master，取决于您的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /www/wwwroot/questions_back
            git pull
            docker-compose down
            docker rmi questions-back
            docker-compose up -d --build 